image: eclipse-temurin:21-jdk-noble

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull-push

stages:
  - test
  - visualize
  - package

test:
  stage: test
  script:
    - ./gradlew check jacocoTestReport
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml
      - build/reports/tests/test/
  coverage: '/Branch coverage: \d+\.\d+/'

coverage:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.11
  needs: ["test"]
  script:
    - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/src/main/kotlin/ > build/cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml

package:
  stage: package
  needs: ["test"]
  script:
    - apt-get update && apt-get install -y gettext
    - ./gradlew dist generatePot
  artifacts:
    paths:
      - build/dist/*.jar
      - build/i18n/pot/*.pot
    expire_in: 1 week