name: CI build

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"] # Skip CI on tags, as Release workflow handles that

permissions:
  contents: read

env:
  JAVA_VERSION: '21'
  JAVA_DIST: 'zulu'

jobs:
  assemble:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit

      - name: Execute Gradle assemble
        run: ./gradlew assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: assemble
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run test
        run: ./gradlew check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}