name: Gradle CI

on:
  push:
    branches:
      - "**"  # needed, because otherwise it's triggered for release as well
  pull_request:

permissions:
  contents: read

jobs:
  validation:
    name: Gradle Wrapper validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
  compile:
    needs: validation
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          check-latest: true
          distribution: 'zulu'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
        env:
          GH_PACKAGE_REPO_TOKEN: ${{ secrets.GH_PACKAGE_REPO_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run test
        run: ./gradlew check
        env:
          GH_PACKAGE_REPO_TOKEN: ${{ secrets.GH_PACKAGE_REPO_TOKEN }}