name: Release assets

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  validation:
    name: Gradle Wrapper validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  test:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run test
        run: ./gradlew check
        env:
          GH_PACKAGE_REPO_TOKEN: ${{ secrets.GH_PACKAGE_REPO_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'x64'
      - name: Update repository index
        run: sudo apt-get update
      - name: Install gettext
        run: sudo apt-get install -y gettext
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew dist generatePot
        env:
          GH_PACKAGE_REPO_TOKEN: ${{ secrets.GH_PACKAGE_REPO_TOKEN }}
      - name: Save version to an environment variable
        id: version_info
        run: echo PLUGIN_VERSION="$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.version_info.outputs.PLUGIN_VERSION }}
          body: For summarised changes, see [CHANGELOG.md](CHANGELOG.md).
          fail_on_unmatched_files: true
          files: |
            build/dist/*.jar
            build/i18n/pot/*.pot